import { Component, OnInit, ViewEncapsulation, Input } from '@angular/core';
import 'bootstrap';
import 'jquery';

@Component({
  selector: 'app-card-component',
  templateUrl: './card-component.component.html',
  styleUrls: ['./card-component.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class CardComponentComponent implements OnInit {
  @Input() dataSet;
  public $: any;

  constructor() {}

  chartContextMenu(items: any) {
    delete items['exclude-points-list'];
    delete items['select-marquee-start'];
    delete items['include'];
    delete items['keep-only'];
    delete items['full-screen-separator'];
    delete items['about'];
    delete items['exclude-points-separator'];
    delete items['select-marquee-separator'];
    delete items['exporting-separator'];
    delete items['exclude-points-keep-only'];
    delete items['exclude-points-point'];
    delete items['chart-with-series-point-separator'];
    items['save-chart-as'].text = 'Export as image...';
    items['save-data-as'].text = 'Export chart data as...';
    return items;
  }

  ngOnInit() {
    var chartTypeData = [];
    chartTypeData = [
      [
        'Testing 1',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 2',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 3',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 4',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 5',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 6',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 7',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 8',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 9',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 10',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 11',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 12',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 13',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 14',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 15',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 16',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 17',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 18',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 19',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 20',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 21',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 22',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 23',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 24',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 25',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 26',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 27',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 28',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 29',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 30',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 31',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 32',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 33',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 34',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 35',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 36',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 37',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 38',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 39',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 40',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 41',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 42',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 43',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 44',
        '79.17',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 45',
        '87.64',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 46',
        '92.86',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 47',
        '91.57',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
      [
        'Testing 48',
        '88.56',
        60,
        100,
        0,
        0,
        0,
        0,
        335,
        26.78,
        13.219999999999,
        10,
      ],
    ];

    anychart.onDocumentReady(function () {
      // Creates Bar chart.
      var data = [
        {
          id: 1,
          x: 'Testing 1',
          oldX: 'Testing 1',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 2,
          x: 'Testing 2',
          oldX: 'Testing 2',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 3,
          x: 'Testing 3',
          oldX: 'Testing 3',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 4,
          x: 'Testing 4',
          oldX: 'Testing 4',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 5,
          x: 'Testing 5',
          oldX: 'Testing 5',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 6,
          x: 'Testing 6',
          oldX: 'Testing 6',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 7,
          x: 'Testing 7',
          oldX: 'Testing 7',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 8,
          x: 'Testing 8',
          oldX: 'Testing 8',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 9,
          x: 'Testing 9',
          oldX: 'Testing 9',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 10,
          x: 'Testing 10',
          oldX: 'Testing 10',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 11,
          x: 'Testing 11',
          oldX: 'Testing 11',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 12,
          x: 'Testing 12',
          oldX: 'Testing 12',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 13,
          x: 'Testing 13',
          oldX: 'Testing 13',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 14,
          x: 'Testing 14',
          oldX: 'Testing 14',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 15,
          x: 'Testing 15',
          oldX: 'Testing 15',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 16,
          x: 'Testing 16',
          oldX: 'Testing 16',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 17,
          x: 'Testing 17',
          oldX: 'Testing 17',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 18,
          x: 'Testing 18',
          oldX: 'Testing 18',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 19,
          x: 'Testing 19',
          oldX: 'Testing 19',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 20,
          x: 'Testing 20',
          oldX: 'Testing 20',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 21,
          x: 'Testing 21',
          oldX: 'Testing 21',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 22,
          x: 'Testing 22',
          oldX: 'Testing 22',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 23,
          x: 'Testing 23',
          oldX: 'Testing 23',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 24,
          x: 'Testing 24',
          oldX: 'Testing 24',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 25,
          x: 'Testing 25',
          oldX: 'Testing 25',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 26,
          x: 'Testing 26',
          oldX: 'Testing 26',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 27,
          x: 'Testing 27',
          oldX: 'Testing 27',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 28,
          x: 'Testing 28',
          oldX: 'Testing 28',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 29,
          x: 'Testing 29',
          oldX: 'Testing 29',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 30,
          x: 'Testing 30',
          oldX: 'Testing 30',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 31,
          x: 'Testing 31',
          oldX: 'Testing 31',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 32,
          x: 'Testing 32',
          oldX: 'Testing 32',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 33,
          x: 'Testing 33',
          oldX: 'Testing 33',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 34,
          x: 'Testing 34',
          oldX: 'Testing 34',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 35,
          x: 'Testing 35',
          oldX: 'Testing 35',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 36,
          x: 'Testing 36',
          oldX: 'Testing 36',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 37,
          x: 'Testing 37',
          oldX: 'Testing 37',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 38,
          x: 'Testing 38',
          oldX: 'Testing 38',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 39,
          x: 'Testing 39',
          oldX: 'Testing 39',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 40,
          x: 'Testing 40',
          oldX: 'Testing 40',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 41,
          x: 'Testing 41',
          oldX: 'Testing 41',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 42,
          x: 'Testing 42',
          oldX: 'Testing 42',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 43,
          x: 'Testing 43',
          oldX: 'Testing 43',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 44,
          x: 'Testing 44',
          oldX: 'Testing 44',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 45,
          x: 'Testing 45',
          oldX: 'Testing 45',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 46,
          x: 'Testing 46',
          oldX: 'Testing 46',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 47,
          x: 'Testing 47',
          oldX: 'Testing 47',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 48,
          x: 'Testing 48',
          oldX: 'Testing 48',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 49,
          x: 'Testing 49',
          oldX: 'Testing 49',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 50,
          x: 'Testing 50',
          oldX: 'Testing 50',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 51,
          x: 'Testing 51',
          oldX: 'Testing 51',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 52,
          x: 'Testing 52',
          oldX: 'Testing 52',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 53,
          x: 'Testing 53',
          oldX: 'Testing 53',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 54,
          x: 'Testing 54',
          oldX: 'Testing 54',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 55,
          x: 'Testing 55',
          oldX: 'Testing 55',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 56,
          x: 'Testing 56',
          oldX: 'Testing 56',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 57,
          x: 'Testing 57',
          oldX: 'Testing 57',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 58,
          x: 'Testing 58',
          oldX: 'Testing 58',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 59,
          x: 'Testing 59',
          oldX: 'Testing 35',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 60,
          x: 'Testing 60',
          oldX: 'Testing 60',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 61,
          x: 'Testing 61',
          oldX: 'Testing 61',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 62,
          x: 'Testing 62',
          oldX: 'Testing 62',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 63,
          x: 'Testing 63',
          oldX: 'Testing 63',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 64,
          x: 'Testing 64',
          oldX: 'Testing 64',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 65,
          x: 'Testing 65',
          oldX: 'Testing 65',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 66,
          x: 'Testing 66',
          oldX: 'Testing 66',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 67,
          x: 'Testing 67',
          oldX: 'Testing 67',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 68,
          x: 'Testing 68',
          oldX: 'Testing 68',
          text: null,
          value: '79.17',
          oldValue: '79.17',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 79.17,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 69,
          x: 'Testing 69',
          oldX: 'Testing 69',
          text: null,
          value: '87.64',
          oldValue: '87.64',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 87.64,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 70,
          x: 'Testing 70',
          oldX: 'Testing 70',
          text: null,
          value: '92.86',
          oldValue: '92.86',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 92.86,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 71,
          x: 'Testing 71',
          oldX: 'Testing 71',
          text: null,
          value: '91.57',
          oldValue: '91.57',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 91.57,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
        {
          id: 72,
          x: 'Testing 72',
          oldX: 'Testing 72',
          text: null,
          value: '88.56',
          oldValue: '88.56',
          min: 0,
          max: 100,
          sdMinus: 0,
          average: 0,
          sdPlus: 0,
          cutOff: 0,
          phaseId: 0,
          uniqueId: 500,
          isClickable: false,
          count: 1180,
          fill: 'rgb(100, 181, 246)',
          stroke: 'rgb(100, 181, 246)',
          size: 2,
          assessmentDate: null,
          dataPoints: [
            {
              label: 'Actual',
              value: 88.56,
            },
            {
              label: 'Min',
              value: 0,
            },
            {
              label: 'Max',
              value: 100,
            },
          ],
          drillDown: [],
          isNewInnovation: null,
          responseText: null,
          isRubric: false,
          name: null,
          title: '',
        },
      ];
      var chart = anychart.bar();
      var credits = chart.credits();
      credits.enabled(false);
      chart.padding([10, 40, 5, 20]);
      chart.animation(true).padding([30, 40, 5, 20]);
      chart.barGroupsPadding(0);
      var xLabels = chart.xAxis().labels();
      xLabels.fontSize(10);
      xLabels.fontWeight(500);
      xLabels.width(185);
      xLabels.hAlign('right');
      xLabels.wordWrap('break-word');
      xLabels.wordBreak('normal');
      var dataSet = anychart.data.set(chartTypeData);
      var series = chart.bar(data);

      var sdOneseriesData = dataSet.mapAs({
        x: 0,
        value: 1,
        valueLowerError: 9,
        valueUpperError: 10,
        id: 8,
      });
      chart
        .jumpLine(sdOneseriesData)
        .markers(false)
        .maxPointWidth(0)
        .color('rgb(100, 181, 246)')
        .error();
      var cohortMinimumseriesData = dataSet.mapAs({ x: 0, value: 2, id: 8 });
      chart
        .jumpLine(cohortMinimumseriesData)
        .selectionMode('none')
        .name('Cohort Minimum')
        .stroke('rgba(0, 0, 0, 0.5)', 5, '0 7 10,15');
      var cohortMaxseriesData = dataSet.mapAs({ x: 0, value: 3, id: 8 });
      chart
        .jumpLine(cohortMaxseriesData)
        .selectionMode('none')
        .name('Cohort Maximum')
        .stroke('rgba(0, 0, 0, 0.5)', 5, '0 7 10,15');

      var labels = series.labels();
      labels.enabled(true);
      labels.fontSize(11);
      labels.fontWeight(500);
      labels.fontColor('white');
      labels.position('center');
      labels.format(function () {
        if (data && data.length > 0) {
          const indexValue = data[this.index];
          if (indexValue && indexValue.isNewInnovation == 1) {
            return indexValue.responseText;
          } else {
            return this.value + '%';
          }
        }
        return '';
      });

      series.tooltip().position('right').anchor('center').offsetX(5).offsetY(0);
      series.tooltip().format(function () {
        if (data && data.length > 0) {
          const indexValue = data[this.index];
          if (indexValue && indexValue.isNewInnovation == 1) {
            return 'Your Score: ' + indexValue.responseText;
          } else if (indexValue && indexValue.isRubric) {
            return 'Raw Score: ' + indexValue.oldValue;
            //return 'Your Score: ' + this.value;
          } else {
            return 'Your Score: ' + this.value + '%';
          }
        } else {
          return 'Cohort Mean: ' + this.value + '%';
        }
      });

      chart.pointWidth(25);
      var noDataLabel = chart.noData().label();
      noDataLabel.enabled(true);
      noDataLabel.text('no data');
      var categoryWidth = 40;
      const offset = 50;
      var chartHeight = categoryWidth * data.length + offset;
      chart.yScale().minimum(0);
      chart.yScale().maximum(110);
      chart.padding([10, 40, 5, 20]);
      chart.yScale().minimum(0).maximum(110);
      chart.contextMenu().itemsFormatter((items) => {
        items = this.chartContextMenu(items);
        return items;
      });
      chart.xAxis().overlapMode('allow-overlap');
      chart.title('Create a Bar chart');
      chart.container('container');
      chart.draw();
    });
  }
}
